spring:
  cloud:
    config:
      uri: http://localhost:8191
  application:
    name: profile-service



  datasource:
    url: jdbc:mysql://localhost:3306/profile_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework: DEBUG



